version: "3.9"

services:
  lgtm:
    image: grafana/otel-lgtm:1.4.0
    container_name: lgtm
    ports:
      - "3001:3000" # Grafana
      - "4317:4317" # OTLP gRPC
      - "4318:4318" # OTLP HTTP
    restart: unless-stopped
